on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test action
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        uses: ./ # Uses an action in the root directory
        id: hello
        with:
          grpcWeb: true
          additionalLoginOptions: "--config /tmp/.argocd/config"
          server: "argocd.fake.com"
          username: "fakeuser"
          password: "fakepwd"
          subcommand: "app"
          subcommandArgs: "list"
          echoOnly: true
      - name: Check ArgoCD Cli
        run: |
          RESULT=$(which ${{ steps.hello.outputs.argocd }})
          if [[ "$RESULT" != "/tmp/argocd" ]]; then
            echo "Expect steps.hello.outputs.argocd to be '/tmp/argocd'"
            exit 1
          fi
