on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test action
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Setup
        uses: ./ # Uses an action in the root directory
        id: hello
        with:
          grpcWeb: true
          additionalLoginOptions: "--config /tmp/.argocd/config"
          server: "argocd.fake.com"
          username: "fakeuser"
          password: "fakepwd"
          subcommand: "app"
          subcommandArgs: "list"
          echoOnly: true
      - name: Check ArgoCD Cli
        run: which ${{ steps.hello.outputs.argocd }}
